const constants = {
	FETCH_TICKETS_START: 'FETCH_TICKETS_START',
	FETCH_TICKETS_SUCCESS: 'FETCH_TICKETS_SUCCESS',
	FETCH_TICKETS_ERROR: 'FETCH_TICKETS_ERROR',
	CHANGE_VALUTA: 'CHANGE_VALUTA',
	SORT_STOPS: 'SORT_STOPS',
	FILTER_BY_DEFAULT_STOPS: 'FILTER_BY_DEFAULT_STOPS',
	FILTER_BY_STOPS: 'FILTER_BY_STOPS',
	FILTER_BY_ONLY_STOPS: 'FILTER_BY_ONLY_STOPS',
	FILTER_BY_ALL_STOPS: 'FILTER_BY_ALL_STOPS'
}

export default constants
