const constants = {
	FETCH_TICKETS_START: 'FETCH_TICKETS_START',
	FETCH_TICKETS_SUCCESS: 'FETCH_TICKETS_SUCCESS',
	FETCH_TICKETS_ERROR: 'FETCH_TICKETS_ERROR',

	SET_TICKETS: 'SET_TICKETS',

	FILTER_BY_DEFAULT_STOPS: 'FILTER_BY_DEFAULT_STOPS',
	FILTER_BY_STOPS: 'FILTER_BY_STOPS',
	FILTER_BY_ONLY_STOPS: 'FILTER_BY_ONLY_STOPS',
	FILTER_BY_ALL_STOPS: 'FILTER_BY_ALL_STOPS',

	FETCH_CURRENCY_START: 'FETCH_CURRENCY_START',
	FETCH_CURRENCY_SUCCESS: 'FETCH_CURRENCY_SUCCESS',
	FETCH_CURRENCY_ERROR: 'FETCH_CURRENCY_ERROR',

	SET_DEFAULT_CURRENCY: 'SET_DEFAULT_CURRENCY',
	SET_BASE_CURRENCY: 'SET_BASE_CURRENCY',
	SET_CURRENCY_RATES: 'SET_CURRENCY_RATES',

	SET_CURRENCY_MODIFIERS: 'SET_CURRENCY_MODIFIERS',
	ADD_CURRENCY_MODIFIER: 'ADD_CURRENCY_MODIFIER',
	REMOVE_CURRENCY_MODIFIER: 'REMOVE_CURRENCY_MODIFIER'
}

export default constants
