const constants = {
	FETCH_TICKETS_START: 'FETCH_TICKETS_START',
	FETCH_TICKETS_SUCCESS: 'FETCH_TICKETS_SUCCESS',
	FETCH_TICKETS_ERROR: 'FETCH_TICKETS_ERROR',

	SET_TICKETS: 'SET_TICKETS',

	FILTER_BY_DEFAULT_STOPS: 'FILTER_BY_DEFAULT_STOPS',
	FILTER_BY_STOPS: 'FILTER_BY_STOPS',
	FILTER_BY_ONLY_STOPS: 'FILTER_BY_ONLY_STOPS',
	FILTER_BY_ALL_STOPS: 'FILTER_BY_ALL_STOPS',

	FETCH_VALUTA_START: 'FETCH_VALUTA_START',
	FETCH_VALUTA_SUCCESS: 'FETCH_VALUTA_SUCCESS',
	FETCH_VALUTA_ERROR: 'FETCH_VALUTA_ERROR',

	SET_DEFAULT_VALUTA: 'SET_DEFAULT_VALUTA',
	SET_BASE_VALUTA: 'SET_BASE_VALUTA',
	SET_VALUTA_RATES: 'SET_VALUTA_RATES'
}

export default constants
